version: '3.6'

services:
  logsource_driver:
    container_name: driver
    hostname: driver
    image: httpd:alpine
    links:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: fluentd:24223
        tag: "apache.unsecured"
    networks:
      - efk
    ports:
      - "80:80"
