AlignParameters:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 1800

HashSyntax:
  EnforcedStyle: ruby19

Metrics/MethodLength:
  Max: 45

Metrics/ClassLength:
  Max: 300

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 16

Metrics/CyclomaticComplexity:
  Max: 16

Metrics/ModuleLength:
  Max: 300

Metrics/ParameterLists:
  Max: 6

Metrics/BlockLength:
  Max: 300

Documentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

StringLiterals:
  EnforcedStyle: single_quotes

# enabled due to upstream issue #2876
Style/ConditionalAssignment:
  Enabled: false

Style/MethodMissing:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

AllCops:
  Exclude:
    - '**/*/.kitchen/**/*'
    - '**/*/files/default/vendor/**/*'
