{{- if (empty .Values.existingConfigMap) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fluent-bit.fullname" . }}-certs
  labels:
    app: {{ template "fluent-bit.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  # Certificate files:
  # ==================
{{ (.Files.Glob "certs/*").AsConfig | indent 2 }}
{{- end -}}
