version: '3.6'

services:
  nginx:
    build:
      context: ./nginx
      args:
        VERSION_NGINX: $VERSION_NGINX
    container_name: nginx
    depends_on:
      - kibana
    hostname: nginx
    networks:
      - efk
    ports:
      - "8080:80"
    restart:
      always
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/config/htpasswd.users:/etc/nginx/htpasswd.users
